### ISSUE TITLE
Meeting Posts

### ISSUE THREAD

**Issue by JonOdom** [chda6313/SemesterProject#1]
Title: Conquer A Continent (CaC)

Description: A modified version of Risk designed for either mobile or web-based application

Vision Statement: A fun game to both play and develop

**Comment by BookerLightman** [comment]
The following is my idea for how I want the game to work. It is inspired by the game "Battleground States," itself similar to Risk but with a number of different elements:

http://armorgames.com/play/2453/battleground-states-2008

My idea will vary from Risk in the following ways:

-The map will be a map of the states of the US and the provinces of Canada. 

-At the beginning of one's turn, he can move his 'divisions' to an adjacent state he controls or he can attack an adjacent state controlled by a rival. Either way, a division can only move twice in a turn, after which it is 'out of supplies.'

-At the end of a player's turn the computer will automatically raise a number of divisions for him. These will be raised and located in the states, a state will raise more if it has a larger population. States will raise on average a set number of divisions, the number of divisions raised on any turn will vary. The most northern territories of Canada will not raise any divisions as no one lives there. 

-Players can choose to attack with as many or as few divisions as they have which are on a given state. As in Battleground States, automated dice will be rolled to determine the winner, with one die for every division. The total number will be added up and whoever has a higher number wins. The defender wins in the event of a tie. If the attacker wins he occupies the territory, if the defender wins the attacking divisions are destroyed. 

-Players can leave a territory undefended, if they do so an enemy can capture it by marching in a single division.

My hope with these rules is that the game will take a lot less time to play than Risk and include more strategy than Battleground States.
