### ISSUE TITLE
Week of 2/16 meeting

### ISSUE THREAD

**Issue by chda6313** [chda6313/SemesterProject#2]
I have a midterm Wednesday this week, and Part1 is due Thursday, so we need to meet either Monday or Tuesday. What times work for you guys? and would someone text the fourth guy and make sure he can come this week?

M. from 4-6 or 
T before 3 or after 5

are the best times for me.

**Comment by BookerLightman** [comment]
I can meet today from 4 to 6 or tomorrow after 5.
