### ISSUE TITLE
Part 2: Interview Grading

### ISSUE THREAD

**Issue by chda6313** [chda6313/SemesterProject#3]
Did anyone sign up for a slot yet?

**Comment by JonOdom** [comment]
Do you guys wanna meet up sometime on Tuesday to prepare for the meeting?

**Comment by chda6313** [comment]
Yes. Tuesday at noon work for people?

**Comment by JonOdom** [comment]
Works for me.

**Comment by BookerLightman** [comment]
Works for me but I won't be able to get there until 12:20.

**Comment by JonOdom** [comment]
Reminder of things for tomorrow
- Set up your stand-up statement and post it here for verification
- Get a join.me account just in case

**Comment by zajo2880** [comment]
Last week I looked into software that could host a server for our game such as Heroku. This week I'm looking into software that can hold databases in a server so that we can keep track of all of the players on the server. Obstacle could be that there is no software that does both simultaneously.

**Comment by BookerLightman** [comment]
Where is the meeting tomorrow? 

For tomorrow, I'll say I'll work on:

-Sprites
-The background.
-Firing the bullets, where they hit, ect.

**Comment by chda6313** [comment]
Meeting is in ECCS-112C where the labs are. 2:30-3pm.

Last week I worked informally on getting the bare bones of the game going, such as moving a ship on the standalone webpage. This week I will work on Quality of Life changes, (object oriented so multiple people can play is the big one) as well as continuing to develop the core of the game. I can think of no immediate obstacles.

**Comment by JonOdom** [comment]
Here's my go.

Last week I researched HTML in order potentially expand the webpage and it's functionality. This week I will aim to figure out why the webpage/demo currently doesn't work on some internet browsers, and later help general development.
