### ISSUE TITLE
Meetings

### ISSUE THREAD

**Issue by JonOdom** [chda6313/SemesterProject#4]
I talked to 2 of you guys, and it seem we agreed that the meeting should be moved to Thursday to give us a little more time to potentially get something done. 

So anywho, I suggest we go ahead and push the meeting to Thursday. Thoughts?

**Comment by zajo2880** [comment]
Im okay with that. Thursdays are better for me in general because I am busier at the beginning of the week.

**Comment by JonOdom** [comment]
Everybody free for a meeting this coming Thursday? (Week of 3/28)
